name: Build and Deploy
on:
  push:
    paths-ignore:
      - ".github/**"
jobs:
  build:
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          npm run build
          npx netlify-cli deploy --dir=public --prod
